# Where to put and remove end cities
Worlds:
  - world_the_end
#
RemoveVanillaCities: true
# Time until a city regens (days/hours/minutes)
RegenTime: 0/0/3
# Time until city is available to regen after player leaves (days/hours/minutes)
GracePeriod: 0/0/10
Debug: false