name: MovingEndCities
version: 1.5.0-SNAPSHOT
main: bonn2.movingendcities.Main
api-version: 1.13
author: bonn2
depend:
  - WorldEdit
commands:
  movingendcities:
    permission: movingendcities.use
    usage: /movingendcities [version]
