name: MovingEndCities
version: 1.1-SNAPSHOT
main: bonn2.movingendcities.Main
api-version: 1.13
author: bonn2
depend:
  - WorldEdit
commands:
  newcity:
    permission: movingendcities.create
    usage: /newcity <name>
  removecity:
    permission: movingendcities.remove
    usage: /removecity <name>